[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

[dependencies]
egui-macroquad = "0.15.0"
lazy_static = "1.5.0"
macroquad = "0.3.26"
rand = "0.9.1"
strum = "0.27.1"
strum_macros = "0.27.1"
